baseurl = "http://theanalyst.github.io/"
languageCode = "en-us"
title = "Often Bearing Metaphoric Tense"
DisqusShortname = "hyperbolicmonologues"
paginate = 5
Copyright = "All rights reserved 2012-15"

[params]
description="code,coffee & stuff"
githubName = "theanalyst"
twitterName = "abhishekl"
cover="images/code.png"

[[menu.main]]
name = "Blog"
weight = -120
identifier = "blog"
url = "/"